CREATE TABLE users(
    id INT(11) NOT NULL AUTO_INCREMENT,
    fname VARCHAR(30) NOT NULL ,
    lname VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    pwd VARCHAR(30) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIME
);
